import { CandidateData } from '../CandidatePortal';
import { Link } from 'react-router';
import * as Progress from '@radix-ui/react-progress';
import { BookOpen, Calendar, ArrowLeft, CheckCircle2, TrendingUp, Target } from 'lucide-react';

interface Props {
  candidateData: CandidateData;
}

export function CandidateFeedback({ candidateData }: Props) {
  const score = candidateData.score || 0;
  const isHighScore = score >= 70;

  const roadmap = [
    {
      week: 1,
      title: 'Distributed Systems Fundamentals',
      tasks: [
        'Read "Designing Data-Intensive Applications" chapters 5–7',
        'Complete MIT 6.824 lectures on consensus algorithms',
        'Build a simple key-value store with Raft consensus'
      ]
    },
    {
      week: 2,
      title: 'Microservices Architecture Patterns',
      tasks: [
        'Study saga pattern for distributed transactions',
        'Implement circuit breaker pattern in a sample service',
        'Practice API gateway design with rate limiting'
      ]
    },
    {
      week: 3,
      title: 'Production Systems & Observability',
      tasks: [
        'Set up monitoring with Prometheus & Grafana',
        'Implement distributed tracing with OpenTelemetry',
        'Practice incident response with chaos engineering tools'
      ]
    }
  ];

  return (
    <div className="min-h-screen py-12 px-6">
      <div className="max-w-3xl mx-auto">

        {/* Header */}
        <div className="text-center mb-10">
          <p className="text-xs tracking-[0.2em] uppercase text-[#2d6a55] mb-4">Assessment Complete</p>
          <h1 className="text-[#1c1c1a] mb-2">Your Results</h1>
          <p className="text-sm text-[#6b7063]">
            Thank you for completing the warm-up sandbox, {candidateData.name}
          </p>
        </div>

        {/* Progress */}
        <div className="bg-white border border-[#e4e1da] rounded-2xl p-5 mb-5">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs text-[#6b7063] uppercase tracking-wider">Application Progress</span>
            <span className="text-xs text-[#2d6a55]">Screening Completed</span>
          </div>
          <Progress.Root className="relative overflow-hidden bg-[#f0ede8] rounded-full h-1.5">
            <Progress.Indicator
              className="bg-[#2d6a55] h-full"
              style={{ transform: 'translateX(0%)' }}
            />
          </Progress.Root>
        </div>

        {/* Score Card */}
        <div className="bg-white border border-[#e4e1da] rounded-2xl p-8 mb-5 text-center">
          <div className={`inline-flex items-center justify-center w-24 h-24 rounded-2xl mb-4 ${
            isHighScore ? 'bg-[#e8f2ee]' : 'bg-[#f0ede8]'
          }`}>
            <span className={`text-4xl ${isHighScore ? 'text-[#2d6a55]' : 'text-[#6b7063]'}`}>
              {score}
            </span>
          </div>
          <div className="mb-1">
            <h2 className="text-[#1c1c1a]">
              {isHighScore ? 'Outstanding Performance' : 'Solid Effort'}
            </h2>
          </div>
          <p className="text-sm text-[#6b7063] max-w-md mx-auto leading-relaxed">
            {isHighScore
              ? 'Your responses demonstrate strong technical depth and excellent problem-solving ability. The hiring team will be reviewing your profile shortly.'
              : "Your responses show solid foundational thinking. We've prepared a personalized development roadmap to support your growth."}
          </p>
        </div>

        {/* Qualitative Analysis */}
        <div className="bg-white border border-[#e4e1da] rounded-2xl p-6 mb-5">
          <div className="flex items-center gap-3 mb-5">
            <div className="w-8 h-8 bg-[#e8f2ee] rounded-lg flex items-center justify-center">
              <Target className="w-4 h-4 text-[#2d6a55]" />
            </div>
            <div>
              <h3 className="text-[#1c1c1a]">Performance Analysis</h3>
              <p className="text-xs text-[#6b7063]">Generated by the AI Interview Agent</p>
            </div>
          </div>

          <div className="space-y-3">
            <div className="border-l-2 border-[#2d6a55] bg-[#f0f9f4] rounded-r-xl p-4">
              <p className="text-xs tracking-wider uppercase text-[#2d6a55] mb-2">Key Strengths</p>
              <ul className="space-y-1.5">
                <li className="text-xs text-[#3d5a4a] flex items-start gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-[#2d6a55] flex-shrink-0 mt-0.5" />
                  Clear articulation of technical concepts and trade-offs
                </li>
                <li className="text-xs text-[#3d5a4a] flex items-start gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-[#2d6a55] flex-shrink-0 mt-0.5" />
                  Practical understanding of real-world system constraints
                </li>
                <li className="text-xs text-[#3d5a4a] flex items-start gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-[#2d6a55] flex-shrink-0 mt-0.5" />
                  Thoughtful approach to problem-solving methodology
                </li>
              </ul>
            </div>

            <div className="border-l-2 border-[#c9a84c] bg-[#fdf8ee] rounded-r-xl p-4">
              <p className="text-xs tracking-wider uppercase text-[#c9a84c] mb-2">Growth Opportunities</p>
              <ul className="space-y-1.5">
                <li className="text-xs text-[#5a4d2a] flex items-start gap-2">
                  <TrendingUp className="w-3.5 h-3.5 text-[#c9a84c] flex-shrink-0 mt-0.5" />
                  Deeper exploration of distributed consensus mechanisms
                </li>
                <li className="text-xs text-[#5a4d2a] flex items-start gap-2">
                  <TrendingUp className="w-3.5 h-3.5 text-[#c9a84c] flex-shrink-0 mt-0.5" />
                  More specific examples from production experience
                </li>
                <li className="text-xs text-[#5a4d2a] flex items-start gap-2">
                  <TrendingUp className="w-3.5 h-3.5 text-[#c9a84c] flex-shrink-0 mt-0.5" />
                  Advanced patterns for microservices orchestration
                </li>
              </ul>
            </div>
          </div>
        </div>

        {/* 3-Week Roadmap */}
        <div className="bg-white border border-[#e4e1da] rounded-2xl p-6 mb-5">
          <div className="flex items-center gap-3 mb-5">
            <div className="w-8 h-8 bg-[#e8f2ee] rounded-lg flex items-center justify-center">
              <BookOpen className="w-4 h-4 text-[#2d6a55]" />
            </div>
            <div>
              <h3 className="text-[#1c1c1a]">3-Week Upskilling Roadmap</h3>
              <p className="text-xs text-[#6b7063]">Curated by the Report Agent for your specific growth areas</p>
            </div>
          </div>

          <div className="space-y-3">
            {roadmap.map((week) => (
              <div
                key={week.week}
                className="border border-[#e4e1da] rounded-xl p-5 hover:border-[#2d6a55]/30 transition-colors"
              >
                <div className="flex items-start gap-4">
                  <div className="w-9 h-9 bg-[#f0ede8] rounded-lg flex items-center justify-center flex-shrink-0">
                    <Calendar className="w-4 h-4 text-[#6b7063]" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-xs text-[#a8a49d]">Week {week.week}</span>
                      <span className="text-xs text-[#e4e1da]">—</span>
                      <span className="text-sm text-[#1c1c1a]">{week.title}</span>
                    </div>
                    <ul className="space-y-1.5">
                      {week.tasks.map((task, taskIndex) => (
                        <li
                          key={taskIndex}
                          className="flex items-start gap-2 text-xs text-[#6b7063] leading-relaxed"
                        >
                          <div className="w-1.5 h-1.5 rounded-full bg-[#e4e1da] flex-shrink-0 mt-1.5" />
                          <span>{task}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Next Steps */}
        <div className="bg-[#1c1c1a] rounded-2xl p-8 text-center mb-5">
          <h2 className="text-white mb-3">What Happens Next</h2>
          <p className="text-sm text-[#9a9690] mb-6 max-w-md mx-auto leading-relaxed">
            {isHighScore
              ? 'Our hiring team will review your profile and responses. Expect to hear from us within 3–5 business days regarding next steps.'
              : "While your score didn't meet our current threshold, we encourage you to work through the upskilling roadmap and reapply. We believe in your potential."}
          </p>
          <Link
            to="/"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-white text-[#1c1c1a] rounded-lg hover:bg-[#f7f6f3] transition-colors text-sm"
          >
            <ArrowLeft className="w-4 h-4" />
            Return to Portal Selection
          </Link>
        </div>

        <p className="text-center text-xs text-[#a8a49d]">
          A copy of this feedback has been sent to {candidateData.email}
        </p>

      </div>
    </div>
  );
}
